import Head from 'next/head';
import { increment, decrement } from '@/featrues/counterSlice';
import api from '@/featrues/api';
import Link from 'next/link';
import { useDispatch, useSelector } from 'react-redux';
import { wrapper } from '@/app/store';

export const getStaticProps = wrapper.getStaticProps((store) => async ({ req, res }) => {
	const { dispatch } = store;
	const { data: posts = [], isError, isSuccess, error } = await dispatch(api.endpoints.getPosts.initiate());
	return { props: { posts, isError, isSuccess, error: error ? error : null } };
});

export default function Home({ posts, isError, isSuccess, error }) {
	const dispatch = useDispatch();
	const { count } = useSelector((state) => state.counter);
	const handleClick = () => {
		dispatch(increment());
	};

	const decrementOnClick = () => {
		dispatch(decrement());
	};

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				count: {count}
				<button onClick={handleClick}>Increment</button>
				<button onClick={decrementOnClick}>Decrement</button>
				{isError && <p>{error}</p>}
				<div className='wrapper'>
					<div className='posts'>
						{isSuccess &&
							posts.length &&
							posts.map((post) => (
								<Link href={`/posts/${post.id}`} key={post.id}>
									<div className='post'>
										<h1>{post.title}</h1>
										<h4>post-id: {post.id}</h4>
									</div>
								</Link>
							))}
					</div>
				</div>
			</main>
		</>
	);
}
